-- USE `bjthjgepvhxsr8sdyoxt`;
-- MySQL Script generated by MySQL Workbench
-- Fri Mar 14 18:16:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bjthjgepvhxsr8sdyoxt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bjthjgepvhxsr8sdyoxt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bjthjgepvhxsr8sdyoxt` DEFAULT CHARACTER SET utf8mb3 ;
USE `bjthjgepvhxsr8sdyoxt` ;

-- -----------------------------------------------------
-- Table `bjthjgepvhxsr8sdyoxt`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjthjgepvhxsr8sdyoxt`.`states` (
  `IdState` INT NOT NULL AUTO_INCREMENT,
  `State` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdState`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bjthjgepvhxsr8sdyoxt`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjthjgepvhxsr8sdyoxt`.`cities` (
  `IdCity` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(100) NULL DEFAULT NULL,
  `IdState` INT NOT NULL,
  PRIMARY KEY (`IdCity`),
  INDEX `fk_Cities_States1_idx` (`IdState` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_States1`
    FOREIGN KEY (`IdState`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`states` (`IdState`))
ENGINE = InnoDB
AUTO_INCREMENT = 5575
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bjthjgepvhxsr8sdyoxt`.`signatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjthjgepvhxsr8sdyoxt`.`signatures` (
  `IdSignature` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `RegisterDate` VARCHAR(45) NULL DEFAULT NULL,
  `SignaturePrice` DECIMAL(10,0) NULL DEFAULT NULL,
  `SignatureType` VARCHAR(45) NULL DEFAULT NULL,
  `Genre` VARCHAR(45) NULL DEFAULT NULL,
  `DeadlineSignature` VARCHAR(45) NULL DEFAULT NULL,
  `ImageProfile` VARCHAR(200) NULL DEFAULT NULL,
  `ImageHeader` VARCHAR(200) NULL DEFAULT NULL,
  `ImageFooter` VARCHAR(200) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `Id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdSignature`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bjthjgepvhxsr8sdyoxt`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjthjgepvhxsr8sdyoxt`.`address` (
  `IdAddress` INT NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(45) NULL DEFAULT NULL,
  `Number` VARCHAR(45) NULL DEFAULT NULL,
  `Neighbourhood` VARCHAR(45) NULL DEFAULT NULL,
  `ZipCode` VARCHAR(45) NULL DEFAULT NULL,
  `Complement` VARCHAR(45) NULL DEFAULT NULL,
  `Id` VARCHAR(45) NULL DEFAULT NULL,
  `IdSignature` INT NOT NULL,
  `IdCity` INT NOT NULL,
  PRIMARY KEY (`IdAddress`),
  INDEX `fk_Address_Signatures1_idx` (`IdSignature` ASC) VISIBLE,
  INDEX `fk_Address_Cities1_idx` (`IdCity` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Cities1`
    FOREIGN KEY (`IdCity`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`cities` (`IdCity`),
  CONSTRAINT `fk_Address_Signatures1`
    FOREIGN KEY (`IdSignature`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`signatures` (`IdSignature`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bjthjgepvhxsr8sdyoxt`.`lawyers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjthjgepvhxsr8sdyoxt`.`lawyers` (
  `IdLawyer` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  `Nationality` VARCHAR(45) NULL DEFAULT NULL,
  `CivilStatus` VARCHAR(45) NULL DEFAULT NULL,
  `Profession` VARCHAR(45) NULL DEFAULT NULL,
  `Phone` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `RegisterDate` VARCHAR(45) NULL DEFAULT NULL,
  `LastUpdate` VARCHAR(45) NULL DEFAULT NULL,
  `OabNumber` VARCHAR(45) NULL DEFAULT NULL,
  `OabUf` VARCHAR(2) NULL DEFAULT NULL,
  `Id` VARCHAR(45) NOT NULL,
  `IdSignature` INT NOT NULL,
  `IdAddress` INT NOT NULL,
  `AppPassword` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`IdLawyer`),
  INDEX `fk_Lawyers_Signatures1_idx` (`IdSignature` ASC) VISIBLE,
  INDEX `fk_Lawyers_Address1_idx` (`IdAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Lawyers_Address1`
    FOREIGN KEY (`IdAddress`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`address` (`IdAddress`),
  CONSTRAINT `fk_Lawyers_Signatures1`
    FOREIGN KEY (`IdSignature`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`signatures` (`IdSignature`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bjthjgepvhxsr8sdyoxt`.`bankaccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjthjgepvhxsr8sdyoxt`.`bankaccount` (
  `IdBankAccount` INT NOT NULL AUTO_INCREMENT,
  `BankName` VARCHAR(100) NULL DEFAULT NULL,
  `AccountType` VARCHAR(45) NULL DEFAULT NULL,
  `AgencyNumber` VARCHAR(45) NULL DEFAULT NULL,
  `AccountNumber` VARCHAR(45) NULL DEFAULT NULL,
  `Pix` VARCHAR(45) NULL DEFAULT NULL,
  `PixType` VARCHAR(45) NULL DEFAULT NULL,
  `Id` VARCHAR(45) NULL DEFAULT NULL,
  `IdLawyer` INT NOT NULL,
  `IdSignature` INT NOT NULL,
  PRIMARY KEY (`IdBankAccount`),
  INDEX `fk_BankAccount_Lawyers1_idx` (`IdLawyer` ASC) VISIBLE,
  INDEX `fk_BankAccount_Signatures1_idx` (`IdSignature` ASC) VISIBLE,
  CONSTRAINT `fk_BankAccount_Lawyers1`
    FOREIGN KEY (`IdLawyer`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`lawyers` (`IdLawyer`),
  CONSTRAINT `fk_BankAccount_Signatures1`
    FOREIGN KEY (`IdSignature`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`signatures` (`IdSignature`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bjthjgepvhxsr8sdyoxt`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjthjgepvhxsr8sdyoxt`.`customers` (
  `IdCustomer` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  `Nationality` VARCHAR(45) NULL DEFAULT NULL,
  `CivilStatus` VARCHAR(45) NULL DEFAULT NULL,
  `Profession` VARCHAR(45) NULL DEFAULT NULL,
  `RG` VARCHAR(45) NULL DEFAULT NULL,
  `CpfOrCnpj` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `RegisterDate` VARCHAR(45) NULL DEFAULT NULL,
  `LastUpdate` VARCHAR(45) NULL DEFAULT NULL,
  `Id` VARCHAR(45) NOT NULL,
  `IdSignature` INT NOT NULL,
  `IdAddress` INT NOT NULL,
  PRIMARY KEY (`IdCustomer`),
  INDEX `fk_Customers_Signatures_idx` (`IdSignature` ASC) VISIBLE,
  INDEX `fk_Customers_Address1_idx` (`IdAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Address1`
    FOREIGN KEY (`IdAddress`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`address` (`IdAddress`),
  CONSTRAINT `fk_Customers_Signatures`
    FOREIGN KEY (`IdSignature`)
    REFERENCES `bjthjgepvhxsr8sdyoxt`.`signatures` (`IdSignature`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
